Namespace ShisakuBuhinEdit
    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
    Partial Class Frm41DispShisakuBuhinEdit25
        Inherits System.Windows.Forms.Form

        'フォームがコンポーネントの一覧をクリーンアップするために dispose をオーバーライドします。
        <System.Diagnostics.DebuggerNonUserCode()> _
        Protected Overrides Sub Dispose(ByVal disposing As Boolean)
            Try
                If disposing AndAlso components IsNot Nothing Then
                    components.Dispose()
                End If
            Finally
                MyBase.Dispose(disposing)
            End Try
        End Sub

        'Windows フォーム デザイナで必要です。
        Private components As System.ComponentModel.IContainer

        'メモ: 以下のプロシージャは Windows フォーム デザイナで必要です。
        'Windows フォーム デザイナを使用して変更できます。  
        'コード エディタを使って変更しないでください。
        <System.Diagnostics.DebuggerStepThrough()> _
        Private Sub InitializeComponent()
            Dim TextCellType1 As FarPoint.Win.Spread.CellType.TextCellType = New FarPoint.Win.Spread.CellType.TextCellType
            Dim TextCellType2 As FarPoint.Win.Spread.CellType.TextCellType = New FarPoint.Win.Spread.CellType.TextCellType
            Dim TextCellType3 As FarPoint.Win.Spread.CellType.TextCellType = New FarPoint.Win.Spread.CellType.TextCellType
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Frm41DispShisakuBuhinEdit25))
            Me.FolderBrowserDialog1 = New System.Windows.Forms.FolderBrowserDialog
            Me.Panel2 = New System.Windows.Forms.Panel
            Me.spdParts = New FarPoint.Win.Spread.FpSpread
            Me.spdParts_Sheet1 = New FarPoint.Win.Spread.SheetView
            Me.cmbCloumn = New System.Windows.Forms.ComboBox
            Me.Label3 = New System.Windows.Forms.Label
            Me.Label6 = New System.Windows.Forms.Label
            Me.Panel2.SuspendLayout()
            CType(Me.spdParts, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.spdParts_Sheet1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'Panel2
            '
            Me.Panel2.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
                        Or System.Windows.Forms.AnchorStyles.Left) _
                        Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.Panel2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
            Me.Panel2.Controls.Add(Me.spdParts)
            Me.Panel2.Controls.Add(Me.cmbCloumn)
            Me.Panel2.Controls.Add(Me.Label3)
            Me.Panel2.Controls.Add(Me.Label6)
            Me.Panel2.Location = New System.Drawing.Point(3, 3)
            Me.Panel2.Name = "Panel2"
            Me.Panel2.Size = New System.Drawing.Size(356, 482)
            Me.Panel2.TabIndex = 76
            '
            'spdParts
            '
            Me.spdParts.AccessibleDescription = "spdParts, Sheet1, Row 0, Column 0, "
            Me.spdParts.AllowUserZoom = False
            Me.spdParts.BackColor = System.Drawing.SystemColors.Control
            Me.spdParts.Font = New System.Drawing.Font("ＭＳ ゴシック", 9.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(128, Byte))
            Me.spdParts.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded
            Me.spdParts.Location = New System.Drawing.Point(3, 31)
            Me.spdParts.Name = "spdParts"
            Me.spdParts.RightToLeft = System.Windows.Forms.RightToLeft.No
            Me.spdParts.Sheets.AddRange(New FarPoint.Win.Spread.SheetView() {Me.spdParts_Sheet1})
            Me.spdParts.Size = New System.Drawing.Size(349, 446)
            Me.spdParts.TabIndex = 133
            Me.spdParts.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded
            Me.spdParts.VisualStyles = FarPoint.Win.VisualStyles.[On]
            '
            'spdParts_Sheet1
            '
            Me.spdParts_Sheet1.Reset()
            Me.spdParts_Sheet1.SheetName = "Sheet1"
            'Formulas and custom names must be loaded with R1C1 reference style
            Me.spdParts_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1
            Me.spdParts_Sheet1.ColumnCount = 4
            Me.spdParts_Sheet1.AllowNoteEdit = True
            Me.spdParts_Sheet1.AlternatingRows.Get(0).BackColor = System.Drawing.Color.WhiteSmoke
            Me.spdParts_Sheet1.AlternatingRows.Get(1).BackColor = System.Drawing.Color.WhiteSmoke
            Me.spdParts_Sheet1.AutoGenerateColumns = False
            Me.spdParts_Sheet1.Cells.Get(4, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(4, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(5, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(5, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(6, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(6, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(6, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(6, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(7, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(7, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(7, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Cells.Get(7, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(8, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(8, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(9, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(9, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(10, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(10, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(11, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(11, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(12, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(12, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(13, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(13, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(14, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(14, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(15, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(15, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(16, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(16, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(17, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(17, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(18, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(18, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(19, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(19, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(20, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(20, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(21, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(21, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(22, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(22, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(23, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(23, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(24, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(24, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(25, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(25, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(26, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(26, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(27, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(27, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(28, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(28, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(29, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(29, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(30, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(30, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(31, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(31, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(32, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(32, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(33, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(33, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(34, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(34, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(35, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(35, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(36, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(36, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(37, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(37, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(38, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(38, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(39, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(39, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(40, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(40, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(41, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(41, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(42, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(42, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(43, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(43, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(44, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(44, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(45, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(45, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(46, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(46, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(47, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(47, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(48, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(48, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(49, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(49, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(50, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(50, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(51, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(51, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(52, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(52, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(53, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(53, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(54, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(54, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(55, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(55, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(56, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(56, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(57, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(57, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(58, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(58, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(59, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(59, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(60, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(60, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(61, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(61, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(62, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(62, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(63, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(63, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(64, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(64, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(65, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(65, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(66, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(66, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(67, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(67, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(68, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(68, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(69, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(69, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(70, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(70, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(71, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(71, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(72, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(72, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(73, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(73, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(74, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(74, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(75, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(75, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(76, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(76, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(77, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(77, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(78, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(78, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(79, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(79, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(80, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(80, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(81, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(81, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(82, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(82, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(83, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(83, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(84, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(84, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(85, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(85, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(86, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(86, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(87, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(87, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(88, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(88, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(89, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(89, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(90, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(90, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(91, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(91, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(92, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(92, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(93, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(93, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(94, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(94, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(95, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(95, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(96, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(96, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(97, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(97, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(98, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(98, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(99, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(99, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(100, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(100, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(101, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(101, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(102, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(102, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(103, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(103, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(104, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(104, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(105, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(105, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(106, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(106, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(107, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(107, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(108, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(108, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(109, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(109, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(110, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(110, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(111, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(111, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(112, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(112, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(113, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(113, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(114, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(114, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(115, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(115, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(116, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(116, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(117, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(117, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(118, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(118, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(119, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(119, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(120, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(120, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(121, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(121, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(122, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(122, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(123, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(123, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(124, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(124, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(125, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(125, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(126, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(126, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(127, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(127, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(128, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(128, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(129, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(129, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(130, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(130, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(131, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(131, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(132, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(132, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(133, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(133, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(134, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(134, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(135, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(135, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(136, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(136, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(137, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(137, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(138, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(138, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(139, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(139, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(140, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(140, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(141, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(141, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(142, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(142, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(143, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(143, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(144, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(144, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(145, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(145, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(146, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(146, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(147, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(147, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(148, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(148, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(149, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(149, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(150, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(150, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(151, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(151, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(152, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(152, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(153, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(153, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(154, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(154, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(155, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(155, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(156, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(156, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(157, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(157, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(158, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(158, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(159, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(159, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(160, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(160, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(161, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(161, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(162, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(162, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(163, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(163, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(164, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(164, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(165, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(165, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(166, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(166, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(167, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(167, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(168, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(168, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(169, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(169, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(170, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(170, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(171, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(171, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(172, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(172, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(173, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(173, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(174, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(174, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(175, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(175, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(176, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(176, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(177, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(177, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(178, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(178, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(179, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(179, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(180, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(180, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(181, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(181, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(182, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(182, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(183, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(183, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(184, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(184, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(185, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(185, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(186, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(186, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(187, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(187, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(188, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(188, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(189, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(189, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(190, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(190, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(191, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(191, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(192, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(192, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(193, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(193, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(194, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(194, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(195, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(195, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(196, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(196, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(197, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(197, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(198, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(198, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(199, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(199, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(200, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(200, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(201, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(201, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(202, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(202, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(203, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(203, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(204, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(204, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(205, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(205, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(206, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(206, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(207, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(207, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(208, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(208, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(209, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(209, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(210, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(210, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(211, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(211, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(212, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(212, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(213, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(213, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(214, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(214, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(215, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(215, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(216, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(216, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(217, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(217, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(218, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(218, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(219, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(219, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(220, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(220, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(221, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(221, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(222, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(222, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(223, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(223, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(224, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(224, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(225, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(225, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(226, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(226, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(227, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(227, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(228, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(228, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(229, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(229, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(230, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(230, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(231, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(231, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(232, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(232, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(233, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(233, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(234, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(234, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(235, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(235, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(236, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(236, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(237, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(237, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(238, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(238, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(239, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(239, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(240, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(240, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(241, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(241, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(242, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(242, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(243, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(243, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(244, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(244, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(245, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(245, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(246, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(246, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(247, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(247, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(248, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(248, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(249, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(249, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(250, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(250, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(251, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(251, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(252, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(252, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(253, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(253, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(254, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(254, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(255, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(255, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(256, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(256, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(257, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(257, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(258, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(258, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(259, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(259, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(260, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(260, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(261, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(261, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(262, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(262, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(263, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(263, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(264, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(264, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(265, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(265, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(266, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(266, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(267, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(267, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(268, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(268, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(269, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(269, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(270, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(270, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(271, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(271, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(272, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(272, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(273, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(273, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(274, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(274, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(275, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(275, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(276, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(276, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(277, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(277, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(278, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(278, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(279, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(279, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(280, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(280, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(281, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(281, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(282, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(282, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(283, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(283, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(284, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(284, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(285, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(285, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(286, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(286, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(287, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(287, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(288, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(288, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(289, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(289, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(290, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(290, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(291, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(291, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(292, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(292, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(293, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(293, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(294, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(294, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(295, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(295, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(296, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(296, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(297, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(297, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(298, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(298, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(299, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(299, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(300, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(300, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(301, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(301, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(302, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(302, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(303, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(303, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(304, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(304, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(305, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(305, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(306, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(306, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(307, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(307, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(308, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(308, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(309, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(309, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(310, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(310, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(311, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(311, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(312, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(312, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(313, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(313, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(314, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(314, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(315, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(315, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(316, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(316, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(317, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(317, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(318, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(318, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(319, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(319, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(320, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(320, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(321, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(321, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(322, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(322, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(323, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(323, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(324, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(324, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(325, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(325, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(326, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(326, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(327, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(327, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(328, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(328, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(329, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(329, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(330, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(330, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(331, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(331, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(332, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(332, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(333, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(333, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(334, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(334, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(335, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(335, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(336, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(336, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(337, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(337, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(338, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(338, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(339, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(339, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(340, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(340, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(341, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(341, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(342, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(342, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(343, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(343, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(344, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(344, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(345, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(345, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(346, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(346, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(347, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(347, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(348, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(348, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(349, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(349, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(350, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(350, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(351, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(351, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(352, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(352, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(353, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(353, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(354, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(354, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(355, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(355, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(356, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(356, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(357, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(357, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(358, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(358, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(359, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(359, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(360, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(360, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(361, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(361, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(362, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(362, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(363, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(363, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(364, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(364, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(365, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(365, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(366, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(366, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(367, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(367, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(368, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(368, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(369, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(369, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(370, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(370, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(371, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(371, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(372, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(372, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(373, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(373, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(374, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(374, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(375, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(375, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(376, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(376, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(377, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(377, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(378, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(378, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(379, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(379, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(380, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(380, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(381, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(381, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(382, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(382, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(383, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(383, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(384, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(384, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(385, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(385, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(386, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(386, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(387, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(387, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(388, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(388, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(389, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(389, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(390, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(390, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(391, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(391, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(392, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(392, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(393, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(393, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(394, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(394, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(395, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(395, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(396, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(396, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(397, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(397, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(398, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(398, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(399, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(399, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(400, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(400, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(401, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(401, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(402, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(402, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(403, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(403, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(404, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(404, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(405, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(405, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(406, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(406, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(407, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(407, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(408, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(408, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(409, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(409, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(410, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(410, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(411, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(411, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(412, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(412, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(413, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(413, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(414, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(414, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(415, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(415, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(416, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(416, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(417, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(417, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(418, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(418, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(419, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(419, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(420, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(420, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(421, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(421, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(422, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(422, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(423, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(423, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(424, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(424, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(425, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(425, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(426, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(426, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(427, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(427, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(428, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(428, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(429, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(429, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(430, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(430, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(431, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(431, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(432, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(432, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(433, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(433, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(434, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(434, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(435, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(435, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(436, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(436, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(437, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(437, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(438, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(438, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(439, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(439, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(440, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(440, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(441, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(441, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(442, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(442, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(443, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(443, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(444, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(444, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(445, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(445, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(446, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(446, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(447, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(447, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(448, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(448, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(449, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(449, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(450, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(450, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(451, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(451, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(452, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(452, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(453, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(453, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(454, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(454, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(455, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(455, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(456, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(456, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(457, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(457, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(458, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(458, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(459, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(459, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(460, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(460, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(461, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(461, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(462, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(462, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(463, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(463, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(464, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(464, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(465, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(465, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(466, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(466, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(467, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(467, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(468, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(468, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(469, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(469, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(470, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(470, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(471, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(471, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(472, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(472, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(473, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(473, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(474, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(474, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(475, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(475, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(476, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(476, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(477, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(477, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(478, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(478, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(479, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(479, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(480, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(480, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(481, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(481, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(482, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(482, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(483, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(483, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(484, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(484, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(485, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(485, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(486, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(486, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(487, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(487, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(488, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(488, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(489, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(489, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(490, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(490, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(491, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(491, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(492, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(492, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(493, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(493, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(494, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(494, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(495, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(495, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(496, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(496, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(497, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(497, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(498, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(498, 2).Locked = True
            Me.spdParts_Sheet1.Cells.Get(499, 0).Locked = True
            Me.spdParts_Sheet1.Cells.Get(499, 2).Locked = True
            Me.spdParts_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "LVL"
            Me.spdParts_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "部品番号"
            Me.spdParts_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "部品名称"
            Me.spdParts_Sheet1.Columns.Get(0).CellType = TextCellType1
            Me.spdParts_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center
            Me.spdParts_Sheet1.Columns.Get(0).Label = "LVL"
            Me.spdParts_Sheet1.Columns.Get(0).Locked = True
            Me.spdParts_Sheet1.Columns.Get(0).Tag = "TAG_LEVEL"
            Me.spdParts_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General
            Me.spdParts_Sheet1.Columns.Get(0).Width = 34.0!
            Me.spdParts_Sheet1.Columns.Get(1).CellType = TextCellType2
            Me.spdParts_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Columns.Get(1).Label = "部品番号"
            Me.spdParts_Sheet1.Columns.Get(1).Tag = "TAG_BUHIN_NO"
            Me.spdParts_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center
            Me.spdParts_Sheet1.Columns.Get(1).Width = 150.0!
            Me.spdParts_Sheet1.Columns.Get(2).CellType = TextCellType3
            Me.spdParts_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left
            Me.spdParts_Sheet1.Columns.Get(2).Label = "部品名称"
            Me.spdParts_Sheet1.Columns.Get(2).Locked = True
            Me.spdParts_Sheet1.Columns.Get(2).Tag = "TAG_BUHIN_NAME"
            Me.spdParts_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center
            Me.spdParts_Sheet1.Columns.Get(2).Width = 141.0!
            Me.spdParts_Sheet1.Columns.Get(3).Visible = False
            Me.spdParts_Sheet1.DataAutoSizeColumns = False
            Me.spdParts_Sheet1.OperationMode = FarPoint.Win.Spread.OperationMode.RowMode
            Me.spdParts_Sheet1.RowHeader.Columns.Default.Resizable = False
            Me.spdParts_Sheet1.RowHeader.Visible = False
            Me.spdParts_Sheet1.Rows.Default.Height = 16.0!
            Me.spdParts_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1
            '
            'cmbCloumn
            '
            Me.cmbCloumn.FormattingEnabled = True
            Me.cmbCloumn.Location = New System.Drawing.Point(52, 5)
            Me.cmbCloumn.Name = "cmbCloumn"
            Me.cmbCloumn.Size = New System.Drawing.Size(58, 20)
            Me.cmbCloumn.TabIndex = 132
            '
            'Label3
            '
            Me.Label3.AutoSize = True
            Me.Label3.Font = New System.Drawing.Font("MS UI Gothic", 9.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(128, Byte))
            Me.Label3.Location = New System.Drawing.Point(8, 8)
            Me.Label3.Name = "Label3"
            Me.Label3.Size = New System.Drawing.Size(38, 12)
            Me.Label3.TabIndex = 131
            Me.Label3.Text = "カラム："
            '
            'Label6
            '
            Me.Label6.AutoSize = True
            Me.Label6.Font = New System.Drawing.Font("MS UI Gothic", 9.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(128, Byte))
            Me.Label6.Location = New System.Drawing.Point(5, 5)
            Me.Label6.Name = "Label6"
            Me.Label6.Size = New System.Drawing.Size(0, 12)
            Me.Label6.TabIndex = 10
            '
            'Frm41DispShisakuBuhinEdit25
            '
            Me.AllowDrop = True
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 12.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.BackColor = System.Drawing.SystemColors.Control
            Me.ClientSize = New System.Drawing.Size(362, 489)
            Me.Controls.Add(Me.Panel2)
            Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
            Me.Name = "Frm41DispShisakuBuhinEdit25"
            Me.Padding = New System.Windows.Forms.Padding(3)
            Me.Text = "部品構成一覧"
            Me.TopMost = True
            Me.Panel2.ResumeLayout(False)
            Me.Panel2.PerformLayout()
            CType(Me.spdParts, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.spdParts_Sheet1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub
        Friend WithEvents FolderBrowserDialog1 As System.Windows.Forms.FolderBrowserDialog
        Friend WithEvents Panel2 As System.Windows.Forms.Panel
        Friend WithEvents Label6 As System.Windows.Forms.Label
        Friend WithEvents cmbCloumn As System.Windows.Forms.ComboBox
        Friend WithEvents Label3 As System.Windows.Forms.Label
        Friend WithEvents spdParts As FarPoint.Win.Spread.FpSpread
        Friend WithEvents spdParts_Sheet1 As FarPoint.Win.Spread.SheetView

    End Class
End Namespace
